name: Build and Push

on:
  workflow_dispatch:

concurrency:
  group: "build"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git checkout develop-builds
          git pull origin develop-builds
          git merge origin/develop

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'npm'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.2'

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          java-package: 'jre'

      - name: CI and Prepublish
        run: npm ci

      - name: Commit and Push Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "The blocks of scratch!!!" || echo "No changes to commit"
          git push origin develop-builds
